# Generated by Django 3.2.7 on 2021-10-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizations',
            options={'verbose_name_plural': 'Organizations'},
        ),
    ]
