# Generated by Django 3.2.7 on 2021-10-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name_plural': 'User Profile'},
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='org_name',
            new_name='org_key',
        ),
    ]
