# Generated by Django 3.2.7 on 2021-10-23 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.CharField(choices=[('ys', 'Yes'), ('no', 'No'), ('ID', 'Just An Idea')], max_length=2)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('project_img', models.ImageField(upload_to='img/')),
                ('project_link', models.URLField(help_text='example@example.com')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
