# Generated by Django 3.2.7 on 2021-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='active',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
