# Generated by Django 3.2.7 on 2021-09-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20210907_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='active',
            field=models.CharField(choices=[('ys', 'Yes'), ('no', 'No'), ('ID', 'Just An Idea')], default=None, max_length=2),
        ),
    ]
