# Generated by Django 3.2.7 on 2021-09-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_showcase_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcase',
            name='active',
            field=models.CharField(choices=[('ys', 'Yes'), ('no', 'No'), ('ID', 'Just An Idea')], default='no', max_length=2),
        ),
    ]
