# Generated by Django 3.2.7 on 2021-09-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20210908_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
