# Generated by Django 3.2.7 on 2021-09-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_showcase_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
