# Generated by Django 3.2.7 on 2021-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_showcase_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
