# Generated by Django 3.2.7 on 2021-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_alter_showcase_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
