# Generated by Django 3.2.7 on 2021-09-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_alter_showcase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='featured',
            field=models.BooleanField(blank=True),
        ),
    ]
