# Generated by Django 3.2.7 on 2021-09-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_alter_showcase_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='active',
            field=models.CharField(choices=[('ys', 'Yes'), ('no', 'No'), ('ID', 'Just An Idea')], max_length=2),
        ),
    ]
