# Generated by Django 3.2.7 on 2021-10-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_auto_20211003_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='project_img',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
