# Generated by Django 3.2.7 on 2021-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_alter_showcase_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='project_link',
            field=models.URLField(default=1, help_text='Sanidhya'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcase',
            name='project_img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
