# Generated by Django 3.2.7 on 2021-10-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_showcase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='project_link',
            field=models.URLField(help_text='sanidhya@Sanidhya.com'),
        ),
    ]
